import type { HostConfig } from '../scripts/host-config';

const namlehCodex: HostConfig = {
  name: 'namleh-codex',
  displayName: 'Namleh Codex Test',
  cliCommand: 'codex',
  cliAliases: [],

  globalRoot: '.codex/skills/namleh-gstack',
  localSkillRoot: '.namleh-gstack/skills/namleh-gstack',
  hostSubdir: '.namleh-gstack',
  usesEnvVars: true,

  frontmatter: {
    mode: 'allowlist',
    keepFields: ['name', 'description'],
    descriptionLimit: 1024,
    descriptionLimitBehavior: 'error',
  },

  generation: {
    generateMetadata: true,
    metadataFormat: 'openai.yaml',
    externalSkillPrefix: 'namleh-gstack',
    includeSkills: [
      'gstack',
      'autoplan',
      'browse',
      'canary',
      'context-restore',
      'context-save',
      'cso',
      'design-consultation',
      'design-review',
      'document-generate',
      'document-release',
      'health',
      'investigate',
      'learn',
      'make-pdf',
      'namleh-agent-factory',
      'namleh-agent-observability',
      'namleh-artifact-governor',
      'namleh-authz-audit',
      'namleh-browser-security-bench',
      'namleh-browser-skillify',
      'namleh-design-lab',
      'namleh-design-memory',
      'namleh-docs-publisher',
      'namleh-handoff',
      'namleh-memory-sync',
      'namleh-model-bench',
      'namleh-ops-architect',
      'namleh-ops-autopilot',
      'namleh-ops-product',
      'namleh-pacing-governor',
      'namleh-plugin-cutover',
      'namleh-question-profile',
      'namleh-release-captain',
      'namleh-review-army',
      'namleh-studio-retro',
      'namleh-workflow-qa',
      'office-hours',
      'plan-ceo-review',
      'plan-design-review',
      'plan-devex-review',
      'plan-eng-review',
      'plan-tune',
      'qa',
      'qa-only',
      'retro',
      'review',
      'setup-browser-cookies',
      'ship',
    ],
    skipSkills: ['codex'],
  },

  pathRewrites: [
    { from: '~/.claude/skills/gstack', to: '$GSTACK_ROOT' },
    { from: '~/.gstack', to: '$GSTACK_HOME' },
    { from: '$HOME/.gstack', to: '$GSTACK_HOME' },
    { from: '~/.codex/skills/gstack', to: '~/.codex/skills/namleh-gstack' },
    { from: '$HOME/.codex/skills/gstack', to: '$HOME/.codex/skills/namleh-gstack' },
    { from: '.claude/skills/gstack', to: '.namleh-gstack/skills/namleh-gstack' },
    { from: '.claude/skills/review', to: '.namleh-gstack/skills/namleh-gstack/review' },
    { from: '.claude/skills', to: '.namleh-gstack/skills' },
    { from: '.agents/skills/gstack', to: '.namleh-gstack/skills/namleh-gstack' },
    { from: '.agents/skills', to: '.namleh-gstack/skills' },
  ],

  suppressedResolvers: [
    'DESIGN_OUTSIDE_VOICES',
    'ADVERSARIAL_STEP',
    'CODEX_SECOND_OPINION',
    'CODEX_PLAN_REVIEW',
    'REVIEW_ARMY',
    'GBRAIN_CONTEXT_LOAD',
    'GBRAIN_SAVE_RESULTS',
  ],

  runtimeRoot: {
    globalSymlinks: ['bin', 'browse/dist', 'browse/bin', 'design/dist', 'make-pdf/dist', 'ETHOS.md'],
    globalFiles: {
      'review': ['checklist.md', 'TODOS-format.md'],
    },
  },
  sidecar: {
    path: '.namleh-gstack/skills/namleh-gstack',
    symlinks: ['bin', 'browse', 'design', 'make-pdf', 'review', 'qa', 'ETHOS.md'],
  },

  install: {
    prefixable: false,
    linkingStrategy: 'symlink-generated',
  },

  coAuthorTrailer: 'Co-Authored-By: OpenAI Codex <noreply@openai.com>',
  learningsMode: 'basic',
  stateRoot: '.gstack-namleh',
  operatingInstructions: [
    '- C# is the default language unless the repo clearly calls for another stack.',
    '- Keep credentials in Vault; never ask the user for keys or tokens.',
    '- Re-check authorization at the endpoint/data layer and shape DTOs explicitly.',
    '- Use Confluence/Namleh knowledge as source-of-truth when project context is missing.',
    '- Prefer feature branches and PRs for normal Namleh repos; this gstack fork is allowed to push main directly while it is only a test fork.',
    '- Do not force-push main unless the user explicitly asks.',
  ].join('\n'),
  boundaryInstruction: 'IMPORTANT: Do NOT read or execute any files under ~/.claude/, ~/.agents/, .claude/skills/, .agents/skills/, or .namleh-gstack/skills/. These are agent skill definitions, generated prompt artifacts, or runtime sidecars. Ignore them unless the user explicitly asks to inspect gstack itself. For Namleh work: never ask the user for tokens; credentials come from Vault, do not force-push main, and use owner-managed dev-to-main for normal repos. This gstack test fork may push main directly when the user asks.',
};

export default namlehCodex;
