name: Workflow Lint
on: [push, pull_request]
jobs:
  actionlint:
    runs-on: [self-hosted, Linux, X64, home-lab]
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: rhysd/actionlint@v1.7.11
